- deepxplore环境原来的keras版本：
(deepxplore) ➜  pretrained git:(main) ✗ conda list | grep tens
tensorboard               1.9.0            py27hf484d3e_0    https://mirror.nju.edu.cn/anaconda/pkgs/main
tensorflow                1.2.1                    py27_0    https://mirror.nju.edu.cn/anaconda/pkgs/free
tensorflow-gpu            1.3.0                         0    https://mirror.nju.edu.cn/anaconda/pkgs/free
tensorflow-gpu-base       1.3.0           py27cuda8.0cudnn6.0_1    https://mirror.nju.edu.cn/anaconda/pkgs/free
tensorflow-tensorboard    1.5.1            py27hf484d3e_1    https://mirror.nju.edu.cn/anaconda/pkgs/main
(deepxplore) ➜  pretrained git:(main) ✗ conda list | grep kera               
keras                     2.0.8            py27hd1b5a5b_0    https://mirror.nju.edu.cn/anaconda/pkgs/main



报错：

```shell
    raise ValueError('Improper config format: ' + str(config))
ValueError: Improper config format: {u'l2': 0.0, u'name': u'L1L2Regularizer', u'l1': 9.99999993922529e-09}
```
是keas版本问题，keras2与keras1不兼容。

[1.2.2 network not compatible on 2.0.2 · Issue #6382 · keras-team/keras · GitHub](https://github.com/keras-team/keras/issues/6382)

